In [30]:
import numpy as np

1. Write a function so that the columns of the output matrix are powers of the input
vector.

In [19]:
def vandermonde_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        
        opt_max = np.array([x**(n-i-1) for x in ipvector for i in range(n)]).reshape(ipvector.size, n)
    
    else:
        
        opt_max = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size, n)
        
    return opt_max
        
inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = vandermonde_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = vandermonde_matrix(inputvector,no_col_opmat,True)

In [20]:
op_matx_dec_order

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [22]:
op_matx_inc_order

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [24]:
def moving_average(a, n=3) :
    
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    
    return ret[n - 1:] / n

In [28]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3

mov_avg = moving_average(arr, n)

In [29]:
mov_avg

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])